default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "memo_user" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "memo_password" } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "db" } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 3306 } %>

development:
  <<: *default
  database: memo_app_development

test:
  <<: *default
  database: memo_app_test
  username: <%= ENV.fetch("DATABASE_USERNAME") { "memo_user" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "memo_password" } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "db" } %>

production:
  <<: *default
  database: memo_app_production
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>